name: Build Android APK (online, no local setup)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Create Flutter project structure
        run: |
          flutter --version
          flutter create .
          ls -la

      # ===== Firebase (ตัวเลือก): ใส่ secret เป็นเนื้อ JSON ตรงๆ =====
      - name: Write google-services.json (if provided)
        if: ${{ secrets.FIREBASE_JSON != '' }}
        run: |
          mkdir -p android/app
          cat > android/app/google-services.json << 'EOF'
          $FIREBASE_JSON
          EOF
        env:
          FIREBASE_JSON: ${{ secrets.FIREBASE_JSON }}

      # ===== Keystore (ตัวเลือก): ถ้ามี secret จะเซ็น release ให้อัตโนมัติ =====
      - name: Prepare keystore (if provided)
        if: ${{ secrets.ANDROID_KEYSTORE_BASE64 != '' }}
        run: |
          mkdir -p $HOME/keystores
          echo "$ANDROID_KEYSTORE_BASE64" | base64 -d > $HOME/keystores/upload.jks
          cat <<EOF > android/key.properties
          storePassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword=${{ secrets.ANDROID_KEY_ALIAS_PASSWORD }}
          keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}
          storeFile=$HOME/keystores/upload.jks
          EOF
        env:
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}

      - name: Flutter pub get
        run: flutter pub get

      # หากมี Syncfusion License: ตั้ง secret SYNCFUSION_LICENSE แล้วอ่านด้วย --dart-define (ดูหมายเหตุ)
      - name: Build APK
        run: |
          if [ -n "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" ]; then
            # มี keystore -> สร้าง release แยก ABI
            if [ -n "${{ secrets.SYNCFUSION_LICENSE }}" ]; then
              flutter build apk --release --split-per-abi \
                --dart-define=SYNCFUSION_LICENSE=${{ secrets.SYNCFUSION_LICENSE }}
            else
              flutter build apk --release --split-per-abi
            fi
          else
            # ไม่มี keystore -> สร้าง debug APK ทดสอบได้ทันที
            flutter build apk --debug
          fi

      - name: Upload APK(s)
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: build/app/outputs/flutter-apk/*.apk
